# Generated by Django 3.1.1 on 2020-09-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('base_experience', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_default', models.BooleanField()),
                ('location_area_encounters', models.URLField(max_length=250)),
                ('order', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('abilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokeapi.ability')),
                ('forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokeapi.form')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokeapi.type')),
            ],
        ),
    ]
