# Generated by Django 3.1.1 on 2020-09-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(to='pokeapi.Ability'),
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='forms',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='forms',
            field=models.ManyToManyField(to='pokeapi.Form'),
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokeapi.Type'),
        ),
    ]
