# Generated by Django 3.1.1 on 2020-09-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0002_auto_20200926_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
    ]
